config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :text, presence: true

  def update_post_comments_counter
    post.update_column('comments_counter', post.comments_counter + 1)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# create comments controller class
class CommentsController < ApplicationController
  # create comment for a post
  # new comment

  def new
    @user = current_user
    @comment = @user.posts.find(params[:post_id]).comments.new
  end

  # def create
  #   @user = User.find(params[:user_id])
  #   @comment = @user.posts.find(params[:post_id]).comments.create(comment_params)
  #   # redirect_to user_post_path(@user, @post)
  #   redirect_to user_post_path(@user, @comment.post)
  # end

  def create
    @comment = Comment.new(comment_params)
    @user = current_user
    @comment.user_id = params[:user_id]
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(@comment.user, @comment.post)
      # notifies the user that the comment was created
      flash[:notice] = 'Comment created!'
    else
      render 'new'
    end
  end

  def destroy
    @user = current_user
    @comment = @user.posts.find(params[:post_id]).comments.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment deleted'

    redirect_to user_post_path(@user, @comment.post)
  end

  # private
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/_form.html.erb
<section class="w-50 mx-auto my-5">
  <%= form_with(model: comment, url: { action: "create" }) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation" class="text-danger">
        <h5><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h5>
        <ul class="fst-italic">
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% [:info, :error].each do |key| %>
      <% if flash[key] %>
      <div class="<%= key %>" id="flash">
        <%= flash[key] %>
      </div>
      <% end %>
  <% end %>
    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-dark btn btn-dark my-3"%>
    </div>
  <% end %>
</section>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1 class="mx-auto mt-5 w-25">New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>