config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :title, :text, presence: true

  validates :title, presence: { message: 'Title must not be blank' },
                    length: { maximum: 250, too_long: 'Title must not exceed 250 characters' }
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal: 0
  validates_numericality_of :like_counter, only_integer: true, greater_than_or_equal: 0

  def update_post_counter
    user.update_column('posts_counter', user.posts_counter + 1)
  end

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @user = current_user
    @posts = @user.posts

    @post_comments = @posts.map do |post|
      { id: post.id, comments: post.comments.all }
    end
  end

  # create a new post
  def create
    @user = current_user
    # validate post params
    @post = @user.posts.create(post_params) # create a new post for the user
    # count user's posts
    @post.comments_counter = @post.comments.count
    @post.like_counter = @post.likes.count
    # @user.posts.count
    if @post.save
      flash[:notice] = 'Post created!'
      redirect_to user_posts_path(@user.id)
    else
      flash.now[:alert] = 'Failed to create post!'
      render :new
    end
    # redirect_to user_posts_path(@user) # redirect to the user's posts
  end

  # destroy a post of the current user
  def destroy
    @user = current_user
    @post = @user.posts.find(params[:id])
    @post.comments.destroy_all
    @post.destroy
    flash[:notice] = 'Post deleted'
    redirect_to user_posts_path(@user)
  end
  # new post

  def new
    @user = current_user
    @post = @user.posts.new
  end

  # upadate a post

  def show
    @user = current_user
    @post = @user.posts.find(params[:id])
    @comments = @post.comments # find all comments for this post
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<section class="w-50 mx-auto my-5">

<%= form_with(model: post, url: { action: "create" }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="text fst-italic">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title,  class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark my-3"%>
  </div>
<% end %>

</section>

app/views/posts/_user_header.html.erb
 <%= link_to  user_path(user), class: "d-flex m-4 justify-content-between align-items-center" do %>
         
        <div class="profil">
           <i class="fas fa-user-circle fa-3x"></i>
        </div>
        <div class="user border d-flex align-items-center justify-content-between px-4 bordered">
            <h2><%= user.name%></h2> 
            <div class="p-0 m-0 align-self-end">Number of poste: <%= user.posts.length%></div>
        </div>
  <% end %>

app/views/posts/index.html.erb
<section class="show_user_posts d-flex flex-column">
        <h2 class="mx-auto text-secondary">Posts</h2>
    <div class="user-lists ">
        <%= render "user_header", :user =>@user %>
    </div>
        <div class="alert alert-success">

    <% if flash[:notice]  %>
        <%= flash[:notice] %>
    <% end %>
        </div>   
      
    <div class=posts>
    <% @posts.each do |i|%>
         <div class="post">
             <%
=begin%>
 <%= link_to user_post_path(@user.id, i.id), method: :delete, class: "" do %>
                <div class=" badge bg-danger"><span class=""> <i class="fas fa-trash-alt"></i> </span>Delete</div>
             <% end %> 
<%
=end%>
             <%= link_to user_post_path(@user.id, i),  class: "post-p" do %>

            
                <div class="post-border post-p">
                    <div class="d-flex align-items-center">
                        <h3>Post #<%= i.title %> </h3>
                        <% if can? :distroy, @post %>
                        <span class="m-3 badge bg-danger"><span class=""> <i class="fas fa-trash-alt"></i> </span>Delete</span>
                        <% end %>
                    </div>
                    <p> 
                     <%= i.text%>
                    </p>
                    <div class="comment-num"><span class="m-2"> Comments: <%= i.comments.count%>,</span> 
                        <span class=""> <i class="<%= i.liked || i.likes.count == 0 ? "far fa-heart fa-2x" : "fas fa-heart fa-2x"%>"></i> </span>
                    
                        <span> <%= i.likes.count-1 <= 0 ? 0 :  i.likes.count-1%></span>
                        
                    </div>
                 </div>
                   
            <% end %>
            <div class="post-border mt-2">
                <% @post_comments.find{|e| e[:id] == i[:id]}[:comments].each do |comment|%>
                    <div class="comment d-flex my-2 justify-content-between w-100">
                        <div>Anderson lebon<%= comment.id %> : 
                                <span> 
                                <%= comment.text %>
                            </span>
                        </div>            
                 </div>
                <% end %> 
            </div>
       </div>

    <% end %>
    </div>
    <div class="button d-flex my-3">
        <%= link_to 'Create new post', new_user_post_path(@user.id), class: "btn btn-dark" %>
        <%= link_to 'See all posts', user_posts_path(@user.id), class: "mx-auto justify-self-center btn btn-dark" %>
    </div>
</section>

app/views/posts/new.html.erb
<h1 class="mx-auto mt-5 w-25">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<section class="show_user_posts d-flex flex-column">
    <h2 class="mx-auto text-secondary mb-3">All Posts</h2>
    <div class= "post-details post-border mt-2">
           <div class="d-flex align-items-center">

                <h2>Post #<%= @post.id%> by: <%= @post.title%></h2>  
                <% if can? :distroy, @post %>
                    <%= link_to user_post_path(@user.id, @post.id), method: :delete, class: "" do %>
                        <span class="m-3 badge bg-danger"><span class=""> <i class="fas fa-trash-alt"></i> </span>Delete</span>
                    <% end %>
                <% end %>
           </div>

            
            <div class="comment-num"><span class="m-2"> Comments: <%= @post.comments.count%>,</span> 
             <%= link_to user_post_likes_path(@user.id, @post.id), method: :post, class: "mx-auto justify-self-center" do %>
                <span class=""> <i class="<%= @post.liked || @post.likes.count == 0 ? "far fa-heart fa-2x" : "fas fa-heart fa-2x"%>"></i> </span>
                
               <span><%= @post.likes.count-1 <= 0 ? 0 :  @post.likes.count-1%></span>
             <% end %>
             
             </div>
        <p class="m-2">
            <%= @post.text%>
        </p>
    </div>
    <div class="post-border mt-2">
        <%@comments.each do |comment|%>
            <div class="comment d-flex my-2 justify-content-between w-100">
                 <div>Anderson lebon<%= comment.id %> : 
                        <span> 
                         <%= comment.text %>
                    </span>
                </div>
                <% if can? :distroy, comment %>
                    <%= link_to user_post_comment_path(@user.id, @post.id, comment.id), method: :delete, class: "" do %>
                        <div class=" badge bg-danger"><span class=""> <i class="fas fa-trash-alt"></i> </span>Delete</div>
                    <% end %> 
                <% end %>             
            </div>
        <% end %>
    </div>
    
 
        <%= link_to 'Add a comment', new_user_post_comment_path(@user.id, @post.id), class: "mx-auto my-3 justify-self-center btn btn-primary" %>
</section>